# kubeadm basic values

global:
  licensing:
  # Note: licensing (and therefore system) will not work without a valid clusterGuid value
    clusterGuid: "<lumenvox-to-provide-cluster-guid>"
  defaultNamespace: "lumenvox"
  hostnameSuffix: ".testmachine.com"
  lumenvox:
    ingress:
      className: nginx
    loggingVerbosity: "warn"
    redisTtl: 4h
  image:
    tag: ":6.0"
  rabbitmq:
    enableTLS: false
    connection:
      url: "<ip-address-of-server-running-rabbitmq>"
  redis:
    enableTLS: false
    connection:
      url: "<ip-address-of-server-running-redis>"
  mongodb:
    connection:
      url: "<ip-address-of-server-running-mongodb>"
  postgresql:
    connection:
      url: "<ip-address-of-server-running-postgres>"
      databaseName: "lumenvox_single_db"
      databaseSchema: "public"
  enabled:
    lumenvoxSpeech: true
    lumenvoxVb: false
    lumenvoxCommon: true
  enableItn: false
  asrLanguages:
    - name: "en"
  ttsLanguages:
    - name: "en_us"
      legacyEnabled: false
      voices:
        - name: "jeff"
          version: "3.0"
        - name: "megan"
          version: "3.0"
  vbLanguages:
    - name: "en_US"
      version: "2.1.15"
